"""add_nombre_producto_to_detalles

Revision ID: 175f06509ab4
Revises: ce86818d3b07
Create Date: 2026-05-05 15:03:33.262477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175f06509ab4'
down_revision: Union[str, Sequence[str], None] = 'ce86818d3b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
