"""add_nombre_producto_to_detalles

Revision ID: ce86818d3b07
Revises: dea21a38b7f4
Create Date: 2026-05-05 14:48:59.285505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce86818d3b07'
down_revision: Union[str, Sequence[str], None] = 'dea21a38b7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalles_pedido', sa.Column('nombre_producto', sa.String(length=255), nullable=False, comment='Nombre del producto copiado desde production_service al momento de la venta.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalles_pedido', 'nombre_producto')
    # ### end Alembic commands ###
