"""add_mesa_inventario_extend_pedido

Revision ID: dea21a38b7f4
Revises: 
Create Date: 2026-05-05 10:23:41.991154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea21a38b7f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre descriptivo del punto de venta (ej: Caja Principal)'),
    sa.Column('estado', sa.Enum('Activa', 'Inactiva', name='estado_caja'), nullable=False, comment='Indica si el punto de venta está habilitado para operar'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cajas_id'), 'cajas', ['id'], unique=False)
    op.create_table('inventario_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto_origen', sa.Integer(), nullable=False, comment='ID del producto en el production_service (referencia externa, sin FK de BD).'),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False, comment='Nombre del producto copiado desde production_service al momento de su recepción.'),
    sa.Column('categoria', sa.Enum('Carnes', 'Vegetales', 'Lacteos', 'Bebidas', 'Especias', name='categoria_inventario_enum'), nullable=False, comment='Categoría del insumo para agrupar en la vista de inventario del salón.'),
    sa.Column('cantidad_actual', sa.Numeric(precision=10, scale=3), nullable=False, comment='Cantidad disponible actualmente. Se incrementa con recepciones y decrementa con ventas.'),
    sa.Column('unidad', sa.String(length=20), nullable=False, comment='Unidad de medida (kg, L, unidad, etc.).'),
    sa.Column('min_stock', sa.Numeric(precision=10, scale=3), nullable=False, comment='Umbral mínimo. Si cantidad_actual < min_stock, se considera stock crítico.'),
    sa.Column('max_stock', sa.Numeric(precision=10, scale=3), nullable=False, comment='Umbral máximo de almacenamiento.'),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False, comment='Costo por unidad. Snapshot del último precio recibido.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última actualización del registro (por recepción o ajuste).'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_local_id'), 'inventario_local', ['id'], unique=False)
    op.create_index(op.f('ix_inventario_local_id_producto_origen'), 'inventario_local', ['id_producto_origen'], unique=False)
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False, comment='Número visible de mesa. Único por restaurante.'),
    sa.Column('capacidad', sa.Integer(), nullable=False, comment='Cantidad máxima de comensales que admite la mesa.'),
    sa.Column('forma', sa.Enum('square', 'circle', name='forma_mesa_enum'), nullable=False, comment='Forma geométrica de la mesa para el mapa visual del salón.'),
    sa.Column('zona', sa.Enum('Interior', 'Terraza', 'VIP', 'Barra', name='zona_mesa_enum'), nullable=False, comment='Área del restaurante donde está ubicada la mesa.'),
    sa.Column('estado_actual', sa.Enum('Libre', 'Ocupado', 'Reservado', 'Atencion', name='estado_mesa_enum'), nullable=False, comment='Estado en tiempo real de la mesa. Se actualiza con cada acción del staff.'),
    sa.Column('id_mesero_asignado', sa.Integer(), nullable=True, comment='ID del empleado-mesero asignado (referencia externa al rh_service, sin FK de BD).'),
    sa.Column('timestamp_ocupacion', sa.DateTime(), nullable=True, comment="Momento en que la mesa pasó a estado 'Ocupado'. Usado para calcular duración del servicio."),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de alta de la mesa en el sistema.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Última modificación del registro.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_index(op.f('ix_mesas_id_mesero_asignado'), 'mesas', ['id_mesero_asignado'], unique=False)
    op.create_index(op.f('ix_mesas_numero'), 'mesas', ['numero'], unique=True)
    op.create_table('recepciones_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_inventario_local', sa.Integer(), nullable=False, comment='Insumo del inventario local al que se suma la recepción.'),
    sa.Column('cantidad_recibida', sa.Numeric(precision=10, scale=3), nullable=False, comment='Cantidad recibida en esta recepción. Se suma a inventario_local.cantidad_actual.'),
    sa.Column('id_produccion_origen', sa.Integer(), nullable=True, comment='ID del despacho o lote en production_service (referencia externa, nullable si es ajuste manual).'),
    sa.Column('recibido_por', sa.Integer(), nullable=False, comment='ID del empleado que firmó la recepción (referencia externa al rh_service).'),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=False, comment='Fecha y hora exacta en que se registró la recepción.'),
    sa.Column('notas', sa.Text(), nullable=True, comment="Observaciones sobre el despacho (ej: 'producto con leve magulladura', 'faltó 0.5 kg')."),
    sa.ForeignKeyConstraint(['id_inventario_local'], ['inventario_local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepciones_stock_id'), 'recepciones_stock', ['id'], unique=False)
    op.create_index(op.f('ix_recepciones_stock_id_inventario_local'), 'recepciones_stock', ['id_inventario_local'], unique=False)
    op.create_table('sesiones_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_caja', sa.Integer(), nullable=False, comment='Caja física/lógica sobre la que opera este turno'),
    sa.Column('id_usuario', sa.Integer(), nullable=False, comment='ID del empleado que abrió la sesión (referencia al rh_service)'),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False, comment='Timestamp exacto en que se abrió la caja'),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True, comment='Timestamp de cierre. NULL mientras la sesión esté abierta'),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False, comment='Dinero en efectivo con el que inicia el turno (fondo de cambio)'),
    sa.Column('monto_declarado_cierre', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monto que el cajero declara tener al cerrar'),
    sa.Column('monto_calculado_cierre', sa.Numeric(precision=10, scale=2), nullable=True, comment='Monto que el sistema calcula: inicial + ingresos − egresos'),
    sa.Column('estado', sa.Enum('Abierta', 'Cerrada', 'Descuadrada', name='estado_sesion'), nullable=False, comment='Descuadrada cuando declarado != calculado al cierre'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_caja'], ['cajas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_caja_id'), 'sesiones_caja', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_id_caja'), 'sesiones_caja', ['id_caja'], unique=False)
    op.create_index(op.f('ix_sesiones_caja_id_usuario'), 'sesiones_caja', ['id_usuario'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False, comment='Sesión de caja activa al momento de crear el pedido'),
    sa.Column('id_mesero', sa.Integer(), nullable=True, comment='ID del empleado-mesero asignado (referencia al rh_service)'),
    sa.Column('id_mesa', sa.Integer(), nullable=True, comment='Mesa asignada al pedido. FK a la tabla mesas (puede ser null para pedidos para llevar/barra).'),
    sa.Column('cubiertos', sa.Integer(), nullable=True, comment='Número de comensales en la mesa. Informativo para cocina.'),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False, comment='Timestamp de creación del pedido'),
    sa.Column('estado_pedido', sa.Enum('Pendiente', 'En Preparacion', 'Servido', 'Pagado', 'Anulado', name='estado_pedido_enum'), nullable=False, comment='Ciclo de vida del pedido desde su creación hasta el cobro'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Suma de los subtotales de las líneas antes de impuestos y descuentos.'),
    sa.Column('impuestos', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto de impuestos aplicados (ej: IVA 10.5%). Calculado sobre el subtotal.'),
    sa.Column('descuentos', sa.Numeric(precision=10, scale=2), nullable=False, comment='Descuentos aplicados al pedido (cupones, promociones, etc.).'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total final = subtotal + impuestos - descuentos. Se recalcula al agregar/quitar ítems.'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_id_mesa'), 'pedidos', ['id_mesa'], unique=False)
    op.create_index(op.f('ix_pedidos_id_mesero'), 'pedidos', ['id_mesero'], unique=False)
    op.create_index(op.f('ix_pedidos_id_sesion'), 'pedidos', ['id_sesion'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False, comment='Pedido al que pertenece esta línea'),
    sa.Column('id_producto', sa.Integer(), nullable=False, comment='ID del producto en el production_service (referencia externa, sin FK)'),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False, comment='Cantidad pedida (Decimal para permitir medidas fraccionadas, ej: 0.5 kg)'),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio en el momento de la venta (snapshot). No cambia con el catálogo.'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='cantidad × precio_unitario. Calculado en la capa de servicio.'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Instrucciones especiales (ej: sin cebolla, poco hielo)'),
    sa.Column('estacion_cocina', sa.Enum('Fuegos', 'Frios', 'Postres', 'Barra', name='estacion_cocina_enum'), nullable=False, comment='Estación de cocina a la que se envía este ítem. Determina en qué monitor KDS aparece.'),
    sa.Column('estado_preparacion', sa.Enum('Pendiente', 'Listo', 'Entregado', name='estado_preparacion_enum'), nullable=False, comment='Ciclo de preparación visible en la pantalla de cocina'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_pedido_id'), 'detalles_pedido', ['id'], unique=False)
    op.create_index(op.f('ix_detalles_pedido_id_pedido'), 'detalles_pedido', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_detalles_pedido_id_producto'), 'detalles_pedido', ['id_producto'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False, comment='Sesión de caja durante la que ocurrió este movimiento'),
    sa.Column('id_pedido', sa.Integer(), nullable=True, comment='Pedido que origina el movimiento. NULL para retiros/egresos sin pedido asociado.'),
    sa.Column('tipo_movimiento', sa.Enum('Ingreso', 'Egreso', name='tipo_movimiento_enum'), nullable=False, comment='Ingreso suma al balance; Egreso resta'),
    sa.Column('concepto', sa.Enum('Venta', 'Propina', 'Retiro para proveedores', 'Retiro caja menor', 'Ajuste', name='concepto_movimiento_enum'), nullable=False, comment='Categoría descriptiva del movimiento para reportes'),
    sa.Column('metodo_pago', sa.Enum('Efectivo', 'Tarjeta', 'QR', 'Transferencia', name='metodo_pago_enum'), nullable=False, comment="Canal de pago utilizado. Solo 'Efectivo' afecta el cuadre físico de la caja."),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor del movimiento (siempre positivo; tipo_movimiento indica si suma o resta)'),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False, comment='Momento exacto en que se registró el movimiento'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones_caja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_id_pedido'), 'movimientos_caja', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_movimientos_caja_id_sesion'), 'movimientos_caja', ['id_sesion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_id_sesion'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_id_pedido'), table_name='movimientos_caja')
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_detalles_pedido_id_producto'), table_name='detalles_pedido')
    op.drop_index(op.f('ix_detalles_pedido_id_pedido'), table_name='detalles_pedido')
    op.drop_index(op.f('ix_detalles_pedido_id'), table_name='detalles_pedido')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_pedidos_id_sesion'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_mesero'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_mesa'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_sesiones_caja_id_usuario'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_id_caja'), table_name='sesiones_caja')
    op.drop_index(op.f('ix_sesiones_caja_id'), table_name='sesiones_caja')
    op.drop_table('sesiones_caja')
    op.drop_index(op.f('ix_recepciones_stock_id_inventario_local'), table_name='recepciones_stock')
    op.drop_index(op.f('ix_recepciones_stock_id'), table_name='recepciones_stock')
    op.drop_table('recepciones_stock')
    op.drop_index(op.f('ix_mesas_numero'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_id_mesero_asignado'), table_name='mesas')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_inventario_local_id_producto_origen'), table_name='inventario_local')
    op.drop_index(op.f('ix_inventario_local_id'), table_name='inventario_local')
    op.drop_table('inventario_local')
    op.drop_index(op.f('ix_cajas_id'), table_name='cajas')
    op.drop_table('cajas')
    # ### end Alembic commands ###
