"""tabla_postulante_modis

Revision ID: 622456b170b5
Revises: 4eb064f10d4e
Create Date: 2025-11-24 03:11:22.330936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '622456b170b5'
down_revision: Union[str, Sequence[str], None] = '4eb064f10d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postulante', sa.Column('fecha_postulacion', sa.DateTime(), nullable=False))
    op.add_column('postulante', sa.Column('estado_entrevista', sa.String(length=20), nullable=False))
    op.add_column('postulante', sa.Column('fecha_entrevista', sa.DateTime(), nullable=True))
    op.add_column('postulante', sa.Column('modalidad_entrevista', sa.String(length=20), nullable=True))
    op.add_column('postulante', sa.Column('notas_entrevista', sa.Text(), nullable=True))
    op.alter_column('postulante', 'rol_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postulante', 'rol_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('postulante', 'notas_entrevista')
    op.drop_column('postulante', 'modalidad_entrevista')
    op.drop_column('postulante', 'fecha_entrevista')
    op.drop_column('postulante', 'estado_entrevista')
    op.drop_column('postulante', 'fecha_postulacion')
    # ### end Alembic commands ###
