"""modifcaciones para horrios e,pelados

Revision ID: 87025cb9bc80
Revises: c57fa3597cb0
Create Date: 2025-10-27 13:37:49.454973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87025cb9bc80'
down_revision: Union[str, Sequence[str], None] = 'c57fa3597cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_schedules', sa.Column('sucursal_id', sa.Integer(), nullable=False))
    op.add_column('employee_schedules', sa.Column('dias_semana', sa.String(length=20), nullable=False))
    op.add_column('employee_schedules', sa.Column('descripcion', sa.Text(), nullable=True))
    op.alter_column('employee_schedules', 'nombre_horario',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'employee_schedules', 'sucursal', ['sucursal_id'], ['id'])
    op.drop_column('employee_schedules', 'dia_semana')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_schedules', sa.Column('dia_semana', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_schedules', type_='foreignkey')
    op.alter_column('employee_schedules', 'nombre_horario',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('employee_schedules', 'descripcion')
    op.drop_column('employee_schedules', 'dias_semana')
    op.drop_column('employee_schedules', 'sucursal_id')
    # ### end Alembic commands ###
