"""Añadir tabla rol y sucursal corregido

Revision ID: b5e31a93d13c
Revises: 392eaea70125
Create Date: 2025-10-20 00:09:17.053166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e31a93d13c'
down_revision: Union[str, Sequence[str], None] = '392eaea70125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_sucursal', sa.String(length=50), nullable=False),
    sa.Column('fecha_inauguracion', sa.Date(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursal_id'), 'sucursal', ['id'], unique=False)
    op.add_column('employees', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'sucursal', ['sucursal_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'rol_id')
    op.drop_column('employees', 'sucursal_id')
    op.drop_index(op.f('ix_sucursal_id'), table_name='sucursal')
    op.drop_table('sucursal')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
